//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.Words = new HashSet<Word>();
            this.WordTypes = new HashSet<WordType>();
        }
    
        public int ProfileID { get; set; }
        public string ProfileName { get; set; }
        public string ProfileUserName { get; set; }
        public string ProfileUserLastName { get; set; }
        public string ProfileFirstLang { get; set; }
        public string ProfileSecondLang { get; set; }
        public Nullable<int> ProfileTimeInterval { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Word> Words { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WordType> WordTypes { get; set; }
    }
}
