//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public int wordID { get; set; }
        public string wordFirstLang { get; set; }
        public string wordSecondLang { get; set; }
        public int typeID { get; set; }
        public Nullable<int> profileID { get; set; }
    
        public virtual WordType WordType { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
